name: Deploy web to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate new Docker image tag
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          cat <<EOF > .env
          ${{ secrets.DEV_ENV }}
          EOF
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/autolink:${{ env.IMAGE_TAG }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/autolink:${{ env.IMAGE_TAG }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /home/yira/domains/api-autolink.yira.pro/public_html/

            echo "📥 Pulling new Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/autolink:${{ env.IMAGE_TAG }}

            echo "🔄 Updating docker-compose.yml with new image tag..."
            sed -i 's|image: ${{ secrets.DOCKERHUB_USERNAME }}/autolink:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/autolink:${{ env.IMAGE_TAG }}|' docker-compose.yml

            echo "🛑 Stopping existing containers..."
            docker compose rm -fsv project-autolink #le nom du service dans le docker-compose.yml

            echo "🚀 Starting updated containers..."
            docker compose up -d project-autolink

            echo "✅ Deployment complete!"
